# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pushci < Formula
  desc "AI-native CI/CD — zero config, runs on your machine, free forever"
  homepage "https://pushci.dev"
  version "1.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/finsavvyai/push-ci.dev/releases/download/v1.0.2/pushci_1.0.2_darwin_amd64.tar.gz"
      sha256 "b4b0c2e71359d58797421e555286a3eba185c2c08a9eaad016cb40b9440d1511"

      define_method(:install) do
        bin.install "pushci"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/finsavvyai/push-ci.dev/releases/download/v1.0.2/pushci_1.0.2_darwin_arm64.tar.gz"
      sha256 "1a4966dc548a5d7d922b18dd21ae07854c412782ccf738ca4b5549bfd59d0bbb"

      define_method(:install) do
        bin.install "pushci"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/finsavvyai/push-ci.dev/releases/download/v1.0.2/pushci_1.0.2_linux_amd64.tar.gz"
      sha256 "980bc6f22ea0541828397fff9a967bab094bfe292ef4797dae6c84e56f451977"
      define_method(:install) do
        bin.install "pushci"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/finsavvyai/push-ci.dev/releases/download/v1.0.2/pushci_1.0.2_linux_arm64.tar.gz"
      sha256 "6f57ecf6d03c97b24f741bd35b9f618687bd42d60501b32b56923b87c68d34fa"
      define_method(:install) do
        bin.install "pushci"
      end
    end
  end

  test do
    assert_match "pushci", shell_output("#{bin}/pushci version")
  end
end
