# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pushci < Formula
  desc "AI-native CI/CD — zero config, runs on your machine, free forever"
  homepage "https://pushci.dev"
  version "1.6.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/finsavvyai/pushci-cli/releases/download/v1.6.10/pushci_1.6.10_darwin_amd64.tar.gz"
      sha256 "f9db08ff607d8cefb96873751f5326e5df6835e1aad6deec9f6b0ad24f5819c1"

      define_method(:install) do
        bin.install "pushci"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/finsavvyai/pushci-cli/releases/download/v1.6.10/pushci_1.6.10_darwin_arm64.tar.gz"
      sha256 "bc9bb6e32e4ffb0ae9edc130a5ac8685e9f0c4f90c3614cad02da49a88dccdbd"

      define_method(:install) do
        bin.install "pushci"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/finsavvyai/pushci-cli/releases/download/v1.6.10/pushci_1.6.10_linux_amd64.tar.gz"
      sha256 "c31eee9d8783b2cedbe0bac2bdaf8ab7370cd62ae365ae347058ac5520f728c3"
      define_method(:install) do
        bin.install "pushci"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/finsavvyai/pushci-cli/releases/download/v1.6.10/pushci_1.6.10_linux_arm64.tar.gz"
      sha256 "57a968a02b765d70cecbee2495d63c9891f0b77805eed2caae7e4e5205825d25"
      define_method(:install) do
        bin.install "pushci"
      end
    end
  end

  test do
    assert_match "pushci", shell_output("#{bin}/pushci version")
  end
end
