# This file was generated by the PushCI signed release flow. DO NOT EDIT.
cask "pushci" do
  version "1.12.10"

  on_macos do
    on_intel do
      sha256 "459532d582b826e3c6917ba2bb32bcd883313f17029e5b6b876ae08adaf13a5a"
      url "https://github.com/finsavvyai/pushci-cli/releases/download/v#{version}/pushci_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/finsavvyai/pushci-cli/"
    end
    on_arm do
      sha256 "1b4a8443132ee1aad85b064d8c8310524bdeca92db05df05597941b23f2ec6de"
      url "https://github.com/finsavvyai/pushci-cli/releases/download/v#{version}/pushci_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/finsavvyai/pushci-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "a683f95aa9ce9863c6c5b7aee508f9e65a3cdf2a27e61cece7a8a0def90e44ba"
      url "https://github.com/finsavvyai/pushci-cli/releases/download/v#{version}/pushci_#{version}_linux_amd64.tar.gz",
        verified: "github.com/finsavvyai/pushci-cli/"
    end
    on_arm do
      sha256 "627d561b24a8194d511acc357c265fc612cd67db0b3778ce5360f48ff047732d"
      url "https://github.com/finsavvyai/pushci-cli/releases/download/v#{version}/pushci_#{version}_linux_arm64.tar.gz",
        verified: "github.com/finsavvyai/pushci-cli/"
    end
  end

  name "pushci"
  desc "AI-native CI/CD — zero config, runs on your machine, free forever"
  homepage "https://pushci.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pushci"
end
