# This file was generated by GoReleaser. DO NOT EDIT.
cask "pushci" do
  version "1.10.13"

  on_macos do
    on_intel do
      url "https://github.com/finsavvyai/pushci-cli/releases/download/v#{version}/pushci_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/finsavvyai/pushci-cli/"
      sha256 "547fcf231f7b677bba085665b26bcc90b0086e1461f5fea0d0cceb698087dc3d"
    end
    on_arm do
      url "https://github.com/finsavvyai/pushci-cli/releases/download/v#{version}/pushci_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/finsavvyai/pushci-cli/"
      sha256 "d357629edb51997401f02a8ef19e6a998a26e098db5f4475d7674c5c34db10b2"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/finsavvyai/pushci-cli/releases/download/v#{version}/pushci_#{version}_linux_amd64.tar.gz",
        verified: "github.com/finsavvyai/pushci-cli/"
      sha256 "2bc10d8dc6c261d68109894a5a0ae52b7fe317e4010893b96efd6d86482878fe"
    end
    on_arm do
      url "https://github.com/finsavvyai/pushci-cli/releases/download/v#{version}/pushci_#{version}_linux_arm64.tar.gz",
        verified: "github.com/finsavvyai/pushci-cli/"
      sha256 "a6c551f3fcb83250a86078d1e601afbc75ac6c3f5ebf1d223330c866bded9b32"
    end
  end

  name "pushci"
  desc "AI-native CI/CD — zero config, runs on your machine, free forever"
  homepage "https://pushci.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pushci"

  # No zap stanza required

end
