# This file was generated by the PushCI signed release flow. DO NOT EDIT.
cask "pushci" do
  version "1.13.1"

  on_macos do
    on_intel do
      sha256 "dc20f62b2cd024af7490f3a2391269691b50ed146a329e765927ec0dc8c45d5f"
      url "https://github.com/finsavvyai/pushci-cli/releases/download/v#{version}/pushci_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/finsavvyai/pushci-cli/"
    end
    on_arm do
      sha256 "894599ce6a9559d6ab4f8e1e457a3bdfe59c48888b1e351d622cd045e36fce7d"
      url "https://github.com/finsavvyai/pushci-cli/releases/download/v#{version}/pushci_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/finsavvyai/pushci-cli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "97cbc52b3ae775252e8868644c0fd54915175e2f68b93eb1b001f5d05d2c73be"
      url "https://github.com/finsavvyai/pushci-cli/releases/download/v#{version}/pushci_#{version}_linux_amd64.tar.gz",
        verified: "github.com/finsavvyai/pushci-cli/"
    end
    on_arm do
      sha256 "fcf8dd8251170eb718393fee581a17afd7147277694c02c55b472b6f996c46cf"
      url "https://github.com/finsavvyai/pushci-cli/releases/download/v#{version}/pushci_#{version}_linux_arm64.tar.gz",
        verified: "github.com/finsavvyai/pushci-cli/"
    end
  end

  name "pushci"
  desc "AI-native CI/CD — zero config, runs on your machine, free forever"
  homepage "https://pushci.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pushci"
end
